version: '3.9'
services:
  server:
    image: mazenamria/server:v1.0
    stdin_open: true
    tty: true
    network_mode: host
    environment:
      DB_HOST: 192.168.204.169
      DB_PORT: 27017
      DB_NAME: stats
      DB_USER: admin
      DB_PASSWORD: admin
      HOST_USER: root
      HOST_PASSWORD: root
