version: "3.9" 
services:
  server:
    image: mazenamria/server:v1.0
    ports:
      - "5000:5000"
    environment:
      DB_HOST: 192.168.205.18
      DB_PORT: 27017
      DB_NAME: monitor
      DB_COLLECTION: stats
      DB_USER: admin
      DB_PASSWORD: admin
    volumes:
      - /proc:/etc/__host_proc__
