version: "3.9" 
services:
  db:
    image: bitnami/mongodb
    ports:
      - "27017:27017"
    environment:
      MONGODB_USERNAME: admin
      MONGODB_PASSWORD: admin
      MONGODB_DATABASE: monitor
